GET http://localhost:5000/
###
GET http://localhost:5000/cobcategory


###
GET http://localhost:5000/api/auth/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjgsImlhdCI6MTY5MDg4MjYzMiwiZXhwIjoxNjkxNDg3NDMyfQ.KeUD2S9sSqpaO2LW68IIXPgHVD93lOJX_21oQFp84xA

###
Post http://localhost:5000/api/auth/register
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjgsImlhdCI6MTY5MDg4MjYzMiwiZXhwIjoxNjkxNDg3NDMyfQ.KeUD2S9sSqpaO2LW68IIXPgHVD93lOJX_21oQFp84xA

{
    "username": "sx123456789102",
    "password": "123456"
}

###
Post http://localhost:5000/api/auth/login/
Content-Type: application/json

{
    "username": "vq12346",
    "password": "123456"
}
###
GET http://localhost:5000/api/post

###
GET http://localhost:5000/api/post/postId/123

###
GET http://localhost:5000/api/post/category/design-art-multimedia


### 
GET http://localhost:5000/api/user/jobs-profile/8

### 
GET http://localhost:5000/api/ntd/company-profile/8


###
GET http://localhost:5000/api/user/resume/headline/8


###
GET http://localhost:5000/api/user/resume/key-skill/8

###
GET http://localhost:5000/api/user/resume/employment/8

###
GET http://localhost:5000/api/user/resume/education/8

###
GET http://localhost:5000/api/user/resume/it-skill/8

###
GET http://localhost:5000/api/user/resume/project/8

###
GET http://localhost:5000/api/user/resume/profile-sumary/8


/// /:id/:property   profile / work / white-paper / presentation / patent / certification
###
GET http://localhost:5000/api/user/resume/accomplishment/8/work

/// get accompkimrnt by userID
###
GET http://localhost:5000/api/user/resume/accomplishment/8


###
GET http://localhost:5000/api/user/resume/desired/8

###
GET http://localhost:5000/api/user/resume/personal-detail/8

###
GET http://localhost:5000/api/user/resume/attack-resume/8

###
Post http://localhost:5000/api/file/extractFile

// --------------------------------------------------------------------------------------------------------------------------------------------


###
GET http://localhost:5000/api/post/coordinate
Content-Type: application/json

{
    "lat": 20.30692732755825,
    "lng": 105.57861328125001,
    "radius": 18965.728225521776
}

###
get http://localhost:5000/api/address/coordinates
Content-Type: application/json

{
    "address": "Co.opMart BMC, Đường Lũy Bán Bích, Phu Tho Hoa Ward, Hồ Chí Minh City, Vietnam"
}

###
POST http://localhost:5000/api/post/toado
Content-Type: application/json

{
    "postId": 125,
    "address": "330 Lê Thị Riêng, Thới An"
}

###
DELETE  http://localhost:5000/api/post/toado
Content-Type: application/json

{
    "postId": 125
}
###
POST http://localhost:5000/api/post/category
Content-Type: application/json

{
    "postId": 124,
    "categoryId": 6
}

###
DELETE http://localhost:5000/api/post/category
Content-Type: application/json

{
    "postId": 124,
    "categoryId": 6
}

###
DELETE http://localhost:5000/api/post/delete-all-category
Content-Type: application/json

{
    "postId": 124
}

###
PUT http://localhost:5000/api/post/124
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjgsImlhdCI6MTY5MjY5NjI1MSwiZXhwIjoxNjkzMzAxMDUxfQ.oDQt0to4VQVH7buqFq3i4sz0T0RVQnDyIVL21apbqqk

{
    "href": "/cong-ty-abc",
    "PostTitle": "Tuyển dụng nhân sự" 
}


###
POST http://localhost:5000/api/post/chedo
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjgsImlhdCI6MTY5MjY5NjI1MSwiZXhwIjoxNjkzMzAxMDUxfQ.oDQt0to4VQVH7buqFq3i4sz0T0RVQnDyIVL21apbqqk

{
    "IDPost": 237,
    "cheDo": 1
}


###
DELETE  http://localhost:5000/api/post/chedo
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjgsImlhdCI6MTY5MjY5NjI1MSwiZXhwIjoxNjkzMzAxMDUxfQ.oDQt0to4VQVH7buqFq3i4sz0T0RVQnDyIVL21apbqqk

{
    "IDPost": 237,
    "cheDo": 1
}

//Bang che do--------------------------------------------------------------------------------------------------------------------------------------------

###
Get http://localhost:5000/api/chedo

###
Get http://localhost:5000/api/chedo/1

###
Get http://localhost:5000/api/chedo/post/123

###
POst http://localhost:5000/api/chedo
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjgsImlhdCI6MTY5MjY5NjI1MSwiZXhwIjoxNjkzMzAxMDUxfQ.oDQt0to4VQVH7buqFq3i4sz0T0RVQnDyIVL21apbqqk

{
    "ten": "Lương tháng 14",
    "icon": "Lương",
    "href": "/luong-thang-14"
}

###
PUT http://localhost:5000/api/chedo/6
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjgsImlhdCI6MTY5MjY5NjI1MSwiZXhwIjoxNjkzMzAxMDUxfQ.oDQt0to4VQVH7buqFq3i4sz0T0RVQnDyIVL21apbqqk

{
    "ten": "Thưởng tết2",
    "icon": "Lương",
    "href": "/luong-thang-14"
}

###
DELETE  http://localhost:5000/api/chedo/5
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjgsImlhdCI6MTY5MjY5NjI1MSwiZXhwIjoxNjkzMzAxMDUxfQ.oDQt0to4VQVH7buqFq3i4sz0T0RVQnDyIVL21apbqqk


//Bang Vị trí tuyển dụng--------------------------------------------------------------------------------------------------------------------------------------------

###
Get http://localhost:5000/api/vttd

###
Get http://localhost:5000/api/vttd/3

###
Get http://localhost:5000/api/vttd/post/123

###
POst http://localhost:5000/api/vttd
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjgsImlhdCI6MTY5MjY5NjI1MSwiZXhwIjoxNjkzMzAxMDUxfQ.oDQt0to4VQVH7buqFq3i4sz0T0RVQnDyIVL21apbqqk

{
    "ten": "DepOps",
    "icon": "developers",
    "href": "/cong-viec-dev"
}

###
PUT http://localhost:5000/api/vttd/3
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjgsImlhdCI6MTY5MjY5NjI1MSwiZXhwIjoxNjkzMzAxMDUxfQ.oDQt0to4VQVH7buqFq3i4sz0T0RVQnDyIVL21apbqqk

{
    "ten": "DepOps",
    "icon": "setting-icon",
    "href": "/cong-viec-dev"
}

###
DELETE  http://localhost:5000/api/vttd/3
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjgsImlhdCI6MTY5MjY5NjI1MSwiZXhwIjoxNjkzMzAxMDUxfQ.oDQt0to4VQVH7buqFq3i4sz0T0RVQnDyIVL21apbqqk

//Bảng Danh mục công việc --------------------------------------------------------------------------------------------------------------------------------------------

###
Get http://localhost:5000/api/danhmuc

###
Get http://localhost:5000/api/danhmuc/2

###
POst http://localhost:5000/api/danhmuc
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjgsImlhdCI6MTY5MjY5NjI1MSwiZXhwIjoxNjkzMzAxMDUxfQ.oDQt0to4VQVH7buqFq3i4sz0T0RVQnDyIVL21apbqqk

{
    "ten": "Bank",
    "icon": "bank-icon",
    "href": "/cong-viec-ngan-hang"
}

###
PUT http://localhost:5000/api/danhmuc/9
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjgsImlhdCI6MTY5MjY5NjI1MSwiZXhwIjoxNjkzMzAxMDUxfQ.oDQt0to4VQVH7buqFq3i4sz0T0RVQnDyIVL21apbqqk

{
    "ten": "Bank",
    "icon": "bank-and-money",
    "href": "/cong-viec-ngan-hang"
}

###
DELETE  http://localhost:5000/api/danhmuc/9
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjgsImlhdCI6MTY5MjY5NjI1MSwiZXhwIjoxNjkzMzAxMDUxfQ.oDQt0to4VQVH7buqFq3i4sz0T0RVQnDyIVL21apbqqk


###

Get http://localhost:5000/api/module/module.tuyendung?href=thuyen-dung-nhan-vien-kinh-doanh-tai-thanh-pho-hcm&id=1
