GET http://localhost:5000/
###
GET http://localhost:5000/cobcategory


###
GET http://localhost:5000/api/auth/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjgsImlhdCI6MTY5MDg4MjYzMiwiZXhwIjoxNjkxNDg3NDMyfQ.KeUD2S9sSqpaO2LW68IIXPgHVD93lOJX_21oQFp84xA

###
Post http://localhost:5000/api/auth/register
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjgsImlhdCI6MTY5MDg4MjYzMiwiZXhwIjoxNjkxNDg3NDMyfQ.KeUD2S9sSqpaO2LW68IIXPgHVD93lOJX_21oQFp84xA

{
    "username": "sx123456789102",
    "password": "123456"
}

###
Post http://localhost:5000/api/auth/login/
Content-Type: application/json

{
    "username": "vq12346",
    "password": "123456"
}
###
GET http://localhost:5000/api/post

###
GET http://localhost:5000/api/post/postId/123

###
GET http://localhost:5000/api/post/category/design-art-multimedia


### 
GET http://localhost:5000/api/user/jobs-profile/8

### 
GET http://localhost:5000/api/ntd/company-profile/8


###
GET http://localhost:5000/api/user/resume/headline/8


###
GET http://localhost:5000/api/user/resume/key-skill/8

###
GET http://localhost:5000/api/user/resume/employment/8

###
GET http://localhost:5000/api/user/resume/education/8

###
GET http://localhost:5000/api/user/resume/it-skill/8

###
GET http://localhost:5000/api/user/resume/project/8

###
GET http://localhost:5000/api/user/resume/profile-sumary/8


/// /:id/:property   profile / work / white-paper / presentation / patent / certification
###
GET http://localhost:5000/api/user/resume/accomplishment/8/work

/// get accompkimrnt by userID
###
GET http://localhost:5000/api/user/resume/accomplishment/8


###
GET http://localhost:5000/api/user/resume/desired/8

###
GET http://localhost:5000/api/user/resume/personal-detail/8

###
GET http://localhost:5000/api/user/resume/attack-resume/8

###
Post http://localhost:5000/api/file/extractFile


###
GET http://localhost:5000/api/post/coordinate
Content-Type: application/json

{
    "lat": 20.90692732755825,
    "lng": 105.57861328125001,
    "radius": 18965.728225521776
}

###
get http://localhost:5000/api/address/coordinates
Content-Type: application/json

{
    "address": "334 Tân Sơn Nhì"
}

###
POST http://localhost:5000/api/post/toado
Content-Type: application/json

{
    "postId": 125,
    "address": "330 Lê Thị Riêng, Thới An"
}

###
DELETE  http://localhost:5000/api/post/toado
Content-Type: application/json

{
    "postId": 125
}
###
POST http://localhost:5000/api/post/category
Content-Type: application/json

{
    "postId": 124,
    "categoryId": 6
}

###
DELETE http://localhost:5000/api/post/category
Content-Type: application/json

{
    "postId": 124,
    "categoryId": 6
}

###
DELETE http://localhost:5000/api/post/delete-all-category
Content-Type: application/json

{
    "postId": 124
}

###
POST http://localhost:5000/api/post/new-post
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjgsImlhdCI6MTY5MjY5NjI1MSwiZXhwIjoxNjkzMzAxMDUxfQ.oDQt0to4VQVH7buqFq3i4sz0T0RVQnDyIVL21apbqqk


