const keywordData = {
  listYeuCauKeyWord: [
    "Yêu cầu ứng viên",
    "yêu cầu ứng viên",
    "Tiêu chí công việc",
    "tiêu chí công việc",
    "Điều kiện ứng tuyển",
    "điều kiện ứng tuyển",
    "Kỹ năng và tiêu chí cần thiết",
    "kỹ năng và tiêu chí cần thiết",
    "Yêu cầu bắt buộc",
    "yêu cầu bắt buộc",
    "Đặc điểm cần có của ứng viên",
    "đặc điểm cần có của ứng viên",
    "Điều kiện tiên quyết công việc",
    "điều kiện tiên quyết công việc",
    "Tiêu chí ứng viên",
    "tiêu chí ứng viên",
    "Yêu cầu cho người ứng tuyển",
    "yêu cầu cho người ứng tuyển",
    "Yêu cầu cụ thể của công việc",
    "yêu cầu cụ thể của công việc",
    "Yêu cầu công việc",
    "yêu cầu công việc",
    "Tiêu chí làm việc",
    "tiêu chí làm việc",
    "Năng lực yêu cầu",
    "năng lực yêu cầu",
    "NĐặc điểm cần có trong công việc",
    "đặc điểm cần có trong công việc",
    "Yêu cầu cho vị trí",
    "yêu cầu cho vị trí",
    "Có kiến thức",
    "có kiến thức",
    "Có kiến thức về",
    "có kiến thức về",
    "Cần có kiến thức",
    "cần có kiến thức",
    "Yêu cầu",
    "yêu cầu",
    "Candidate requirements",
    "candidate requirements",
    "Job qualifications",
    "job qualifications",
    "Applicant prerequisites",
    "applicant prerequisites",
    "Essential skills and qualifications",
    "essential skills and qualifications",
    "Required qualifications",
    "required qualifications",
    "Necessary candidate trai",
    "necessary candidate trai",
    "Job prerequisite",
    "job prerequisite",
    "Candidate criteria",
    "candidate criteria",
    "Job-specific requirement",
    "job-specific requirement",
    "Job requirement",
    "job requirement",
    "Position prerequisites",
    "position prerequisites",
    "Work qualifications",
    "work qualifications",
    "Essential job skills",
    "essential job skills",
    "Required competencies",
    "required competencies",
    "necessary job traits",
    "Necessary job traits",
    "Employment prerequisite",
    "employment prerequisite",
  ],
  listTimeKeyWord: [
    "Thời hạn ứng tuyển",
    "thời hạn ứng tuyển",
    "Thời gian kết thúc ứng tuyển",
    "thời gian kết thúc ứng tuyển",
    "Hạn cuối nộp đơn",
    "hạn cuối nộp đơn",
    "hạn cuối nộp hồ sơ",
    "hạn cuối nộp hồ sơ",
    "Hạn chót nộp đơn",
    "hạn chót nộp đơn",
    "Thời điểm kết thúc ứng tuyển",
    "thời điểm kết thúc ứng tuyển",
    "Ngày kết thúc nộp đơn",
    "ngày kết thúc nộp đơn",
    "Hạn nộp đơn ứng tuyển",
    "hạn nộp đơn ứng tuyển",
    "Hạn nộp hồ sơ ứng tuyển",
    "hạn nộp hồ sơ ứng tuyển",
    "Thời hạn nộp đơn",
    "thời hạn nộp đơn",
    "Thời gian kết thúc nộp hồ sơ",
    "thời gian kết thúc nộp hồ sơ",
    "Ngày cuối nộp hồ sơ",
    "ngày cuối nộp hồ sơ",
    "Ngày kết thúc nộp đơn",
    "ngày kết thúc nộp đơn",
    "Ngày cuối cùng nộp hồ sơ",
    "ngày cuối cùng nộp hồ sơ",
    "Hạn nộp đơn",
    "hạn nộp đơn",
    "Application deadline",
    "application deadline",
    "Submission deadline",
    "submission deadline",
    "Closing date for applications",
    "closing date for applications",
    "Application cutoff date",
    "application cutoff date",
    "Last date to apply",
    "last date to apply",
    "Application end date",
    "application end date",
    "Final date for application submission",
    "final date for application submission",
    "Application due date",
    "application due date",
    "Deadline for applying",
    "deadline for applying",
    "Expiration date",
    "expiration date",
  ],
  listLocationKeyWord: [
    "Địa điểm làm việc cụ thể",
    "địa điểm làm việc cụ thể",
    "Địa điểm làm việc: ",
    "địa điểm làm việc: ",
    "Địa điểm làm việc",
    "địa điểm làm việc",
    "Địa điểm làm việc cụ thể",
    "địa điểm làm việc cụ thể",
    "Chỗ làm việc",
    "chỗ làm việc",
    "Nơi làm việc",
    "nơi làm việc",
    "Văn phòng",
    "văn phòng",
    "Cơ sở:",
    "cơ sở:",
    "Trụ sở chính",
    "trụ sở chính",
    "Địa điểm:",
    "địa điểm:",
    "Địa điểm",
    "địa điểm",
    "Không gian văn phòng",
    "Work venue",
    "work venue",
    "Office space",
    "office space",
    "Workplace",
    "workplace",
    "Work location",
    "work location",
    "Workstation",
    "workstation",
    "Headquarters",
    "headquarters",
    "Headquarter",
    "headquarter",
    "Office",
    "office",
    "Job site",
    "job site",
  ],
  listFulltimeKeyWord: [
    "Làm việc từ thứ 2 đến thứ 6",
    "làm việc từ thứ 2 đến thứ 6",
    "Làm việc từ thứ hai đến thứ sáu",
    "làm việc từ thứ hai đến thứ sáu",
    "Toàn thời gian",
    "toàn thời gian",
    "Từ thứ 2 đến thứ 6",
    "từ thứ 2 đến thứ 6",
    "Từ thứ hai đến thứ sáu",
    "từ thứ hai đến thứ sáu",
    "5 ngày 1 tuần",
    "Năm ngày 1 tuần",
    "năm ngày 1 tuần:",
    "8 tiếng 1 ngày:",
    "Thứ 2- Thứ 6",
    "thứ 2 - thứ 6",
    "Thứ 2 - Thứ 7",
    "thứ 2 - thứ 7",
    "Thứ 2 đến Thứ 7",
    "thứ 2 đến thứ 7",
    "Monday to Friday",
    "monday to friday",
    "Fulltime",
    "fulltime",
    "Full-time",
    "full-time",
    "5 days a week",
    "8 hours a day",
    "40 hours per week",
  ],
  listParttimeKeyWord: [
    "Làm việc bán thời gian",
    "làm việc bán thời gian",
    "Bán thời gian",
    "bán thời gian",
    "Việc làm thời vụ",
    "việc làm thời vụ",
    "Thời vụ",
    "thời vụ",
    "Làm việc theo ca",
    "Giờ làm việc linh hoạt",
    "làm việc theo ca",
    "giờ làm việc linh hoạt",
    "Parttime",
    "Part-time",
    "parttime",
    "part-time",
    "Flexible work",
    "flexible work",
  ],
  listRemoteKeyWord: [
    "Làm việc ở nhà",
    "làm việc ở nhà",
    "Làm việc từ xa",
    "làm việc từ xa",
    "Làm việc trực tuyến",
    "làm việc trực tuyến",
    "Làm việc online",
    "làm việc online",
    "Không cần đến văn phòng",
    "không cần đến văn phòng",
    "không gian và thời gian linh hoạt",
    "Việc làm từ xa",
    "việc làm từ xa",
    "Work from home",
    "work from home",
    "Remote work",
    "remote work",
    "Online work",
    "online work",
    "Virtual work",
    "Flexibility in space and time",
    "flexibility in space and time",
    "Independent work",
    "independent work",
  ],
  listViTriTuyenDungKeyWord: [
    "Tuyển dụng vị trí",
    "tuyển dụng vị trí",
    "Vị trí tuyển dụng",
    "vị trí tuyển dụng",
    "Tuyển vị trí công việc",
    "tuyển vị trí công việc",
    "Vị trí công việc cần tuyển",
    "vị trí công việc cần tuyển",
    "Cơ hội tuyển dụng vị trí",
    "cơ hội tuyển dụng vị trí",
    "Vị trí công việc trống",
    "vị trí công việc trống",
    "Tuyển dụng cho vị trí công việc",
    "tuyển dụng cho vị trí công việc",
    "Vị trí công việc cần tìm kiếm",
    "vị trí công việc cần tìm kiếm",
    "Cơ hội làm việc tại vị trí",
    "cơ hội làm việc tại vị trí",
    "Vị Trí:",
    "Vị trí",
    "vị trí:",
    "vị trí",
    "Position recruitment",
    "position recruitment",
    "Job opening",
    "job opening",
    "Role hiring",
    "role hiring",
    "Position vacancy",
    "position vacancy",
    "Job position recruitment",
    "job position recruitment",
    "Opening for the role",
    "opening for the role",
    "Role vacancy",
    "role vacancy",
    "Hiring for the position",
    "hiring for the position",
    "Position:",
    "position:",
    "Position",
    "position",
    "Position recruitment process",
    "position recruitment process",
  ],
  listMoTaCongViec: [
    "Mô tả công việc:",
    "mô tả công việc:",
    "Mô tả công việc",
    "mô tả công việc",
    "Thông tin về vị trí:",
    "thông tin về vị trí:",
    "Thông tin về vị trí",
    "thông tin về vị trí",
    "Thông tin về công việc:",
    "thông tin về công việc:",
    "Thông tin về công việc",
    "thông tin về công việc",
    "Nhiệm vụ công việc:",
    "nhiệm vụ công việc:",
    "Nhiệm vụ công việc",
    "nhiệm vụ công việc",
    "Tổng quan về vị trí:",
    "tổng quan về vị trí:",
    "Tổng quan về vị trí",
    "tổng quan về vị trí",
    "Các nhiệm vụ công việc:",
    "các nhiệm vụ công việc:",
    "Giới thiệu tổng quát về công việc",
    "giới thiệu tổng quát về công việc",
    "Giới thiệu về công việc",
    "giới thiệu về công việc",
    "Các nhiệm vụ công việc",
    "các nhiệm vụ công việc",
    "Mô tả vị trí:",
    "mô tả vị trí:",
    "Mô tả vị trí",
    "mô tả vị trí",
    "Phạm vi công việc:",
    "phạm vi công việc:",
    "Phạm vi công việc",
    "phạm vi công việc",
    "Tổng quan công việc:",
    "tổng quan công việc:",
    "Tổng quan công việc",
    "tổng quan công việc",
    "Đặc điểm công việc:",
    "đặc điểm công việc:",
    "Đặc điểm công việc",
    "đặc điểm công việc",
    "Job description:",
    "job description:",
    "Job description",
    "job description",
    "Role details:",
    "role details:",
    "Role details",
    "role details",
    "Work responsibilities:",
    "work responsibilities:",
    "Work responsibilities",
    "work responsibilities",
    "Position outline:",
    "position outline:",
    "Position outline",
    "position outline",
    "Workscope:",
    "workscope:",
    "Workscope",
    "workscope",
    "position overview:",
    "Position overview:",
    "Position overview",
    "position overview",
  ],
  listThongTinKhacKeyWord: [
    "Thông tin liên quan",
    "thông tin liên quan",
    "Thông tin bổ sung",
    "thông tin bổ sung",
    "Thông tin lưu ý",
    "thông tin lưu ý",
    "Lưu ý",
    "lưu ý",
    "Liên hệ:",
    "Liên hệ",
    "liên hệ"
  ],
  listMucLuong: [
    "Mức Lương:",
    "mức Lương:",
    "Thang lương:",
    "thang lương:",
    "Khoảng lương:",
    "khoảng lương:",
    "Mức thu nhâp:",
    "mức thu nhập:",
    "Mức lương cơ bản:",
    "mức lương cơ bản:",
    "Thu nhập cơ bản:",
    "thu nhập cơ bản:",
    "Mức thu nhập cơ bản:",
    "mưc thu nhập cơ bản:",
    "Lương:",
    "lương:",
    "Mức Lương",
    "mức Lương",
    "Thang lương",
    "thang lương",
    "Khoảng lương",
    "khoảng lương",
    "Mức thu nhập",
    "mức thu nhập",
    "Mức lương cơ bản",
    "mức lương cơ bản",
    "Thu nhập cơ bản",
    "thu nhập cơ bản",
    "Mức thu nhập cơ bản",
    "mưc thu nhập cơ bản",
    "Lương",
    "lương"
  ],
  dinhDangLuong: ["1000000", "12.000.000", "6 triệu", "6triệu", "12,000,000"],
  nganCachLuong: ["-","đến"]

};

module.exports = { keywordData };
